[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']

auto_detect_solc = true

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config